from django.contrib import admin
from reporting.models import *

class ProductAdmin(admin.ModelAdmin):
	filter_horizontal	= ('code',)

class UnificationAdmin(admin.ModelAdmin):
	filter_horizontal	= ('sapCode', 'jdCode',)

admin.site.register(Sap)
admin.site.register(JD)
admin.site.register(Unification, UnificationAdmin)
admin.site.register(CVM)
admin.site.register(Group)
admin.site.register(SoldTo)
admin.site.register(PSA)
admin.site.register(Country)
admin.site.register(Area)
admin.site.register(Region)
admin.site.register(ShipTo)
admin.site.register(Warehouse)
admin.site.register(ProductName)
admin.site.register(ProductType)
admin.site.register(Package)
admin.site.register(Subpackage)
admin.site.register(ProductFromDB)
admin.site.register(Product, ProductAdmin)
admin.site.register(DeliveryForm)
admin.site.register(DeliveryMethod)
admin.site.register(Transport)
admin.site.register(Office)
admin.site.register(SalesRepresentative)
admin.site.register(Delivery)
admin.site.register(Transaction)
admin.site.register(Prediction)
admin.site.register(ProductionExpense)
admin.site.register(OtherExpense)
admin.site.register(CostType)
admin.site.register(CostElement)
admin.site.register(CostCenter)
admin.site.register(Distribution)
admin.site.register(EBITDA)