from django.contrib import admin
from reporting.models import *

# admin.site.register(Warehouse)
# admin.site.register(ProductName)
# admin.site.register(Package)
# admin.site.register(SubPackage)
# admin.site.register(ProductType)
# admin.site.register(TransportWith)
# admin.site.register(TransportHow)
# admin.site.register(Segment)
# admin.site.register(Country)
# admin.site.register(Area)
# admin.site.register(CustomerAccount)
# admin.site.register(CustomerShipTo)
# admin.site.register(CementProductionType)
# admin.site.register(TransportType)
# admin.site.register(Region)
# admin.site.register(SalesRepresentative)
# admin.site.register(Transaction)
# admin.site.register(Sales)
admin.site.register(Sap)
admin.site.register(JD)
admin.site.register(Unification)
admin.site.register(CVM)
admin.site.register(Group)
admin.site.register(SoldTo)
admin.site.register(PSA)
admin.site.register(Country)
admin.site.register(Area)
admin.site.register(Region)
admin.site.register(ShipTo)
admin.site.register(Warehouse)
admin.site.register(ProductName)
admin.site.register(ProductType)
admin.site.register(Package)
admin.site.register(Subpackage)
admin.site.register(Product)
admin.site.register(DeliveryForm)
admin.site.register(DeliveryMethod)
admin.site.register(Transport)
admin.site.register(Office)
admin.site.register(SalesRepresentative)
admin.site.register(Transaction)
admin.site.register(Prediction)
admin.site.register(Delivery)
admin.site.register(EBITDA)