# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CementProductionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cementProductionCode', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountName', models.CharField(max_length=50, unique=True)),
                ('accountNumber', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerShipTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameShipTo', models.CharField(max_length=50, unique=True)),
                ('numberShipTo', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=50, unique=True)),
                ('commonName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productType', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionName', models.CharField(max_length=30, unique=True)),
                ('regionCode', models.CharField(max_length=3)),
                ('regionDescription', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Area', to_field='area')),
                ('country', models.ForeignKey(default='RU', on_delete=django.db.models.deletion.CASCADE, to='reporting.Country', to_field='country')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('budVolume', models.DecimalField(decimal_places=2, max_digits=15)),
                ('budNetSales', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fcVolume', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fcNetSales', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estVolume', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estNetSales', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cementProductionCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.CementProductionType', to_field='cementProductionCode')),
            ],
        ),
        migrations.CreateModel(
            name='SalesRepresentative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesRepresentative', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subPackage', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shippedVolume', models.DecimalField(decimal_places=2, max_digits=15)),
                ('shippedAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('accountName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.CustomerAccount', to_field='accountName')),
                ('cementProductionCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.CementProductionType', to_field='cementProductionCode')),
            ],
        ),
        migrations.CreateModel(
            name='TransportHow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportHow', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportName', models.CharField(max_length=50, unique=True)),
                ('transportCode', models.CharField(max_length=5, unique=True)),
                ('transportHow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.TransportHow', to_field='transportHow')),
            ],
        ),
        migrations.CreateModel(
            name='TransportWith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportWith', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouseName', models.CharField(max_length=10, unique=True)),
                ('warehouseCode', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='transporttype',
            name='transportWith',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.TransportWith', to_field='transportWith'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='intercompanyFrom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reporting.Warehouse', to_field='warehouseName'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='intercompanyTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.Warehouse', to_field='warehouseName'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='nameShipTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.CustomerShipTo', to_field='nameShipTo'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='regionName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Region', to_field='regionName'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='salesRepresentative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.SalesRepresentative', to_field='salesRepresentative'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transportName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.TransportType', to_field='transportName'),
        ),
        migrations.AddField(
            model_name='customershipto',
            name='segmentShipTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Segment', to_field='segment'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='segmentSoldTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Segment', to_field='segment'),
        ),
        migrations.AddField(
            model_name='cementproductiontype',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Package', to_field='package'),
        ),
        migrations.AddField(
            model_name='cementproductiontype',
            name='productName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.ProductName', to_field='productName'),
        ),
        migrations.AddField(
            model_name='cementproductiontype',
            name='productType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.ProductType', to_field='productType'),
        ),
        migrations.AddField(
            model_name='cementproductiontype',
            name='subPackage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.SubPackage', to_field='subPackage'),
        ),
        migrations.AddField(
            model_name='cementproductiontype',
            name='warehouseName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.Warehouse', to_field='warehouseName'),
        ),
    ]
