# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unification',
            name='jdCode',
            field=models.ManyToManyField(blank=True, to='reporting.JD'),
        ),
        migrations.AlterField(
            model_name='unification',
            name='sapCode',
            field=models.ManyToManyField(blank=True, to='reporting.Sap'),
        ),
    ]
