# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_auto_20160203_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cementproductiontype',
            name='warehouseName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.Warehouse', to_field='warehouseName'),
        ),
    ]
