# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_auto_20160209_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='shippedAmount',
            field=models.DecimalField(decimal_places=2, default='Null', max_digits=15),
            preserve_default=False,
        ),
    ]
