# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_auto_20160209_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebitda',
            name='deliveryRailDistance',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ebitda',
            name='deliveryRoadDistance',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ebitda',
            name='deliveryWaterDistance',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ebitda',
            name='outboundFreightWater',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ebitda',
            name='outboundFreightWater_t',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ebitda',
            name='tKmWater',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
