# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_auto_20160203_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cementproductiontype',
            name='warehouseName',
            field=models.ForeignKey(default='Null', on_delete=django.db.models.deletion.CASCADE, to='reporting.Warehouse', to_field='warehouseName'),
            preserve_default=False,
        ),
    ]
