# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_auto_20160209_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='transportCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Transport', to_field='code'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transportCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Transport', to_field='code'),
        ),
    ]
