# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0008_remove_transport_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='name',
            field=models.CharField(default='Null', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
