# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0011_auto_20160209_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldto',
            name='CVM',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.CVM', to_field='name'),
        ),
    ]
