# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0012_auto_20160209_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
