# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0014_auto_20160209_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthAndYear', models.CharField(max_length=7, unique=True)),
                ('administration', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('marketingAndSales', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthAndYear', models.CharField(max_length=7, unique=True)),
                ('variable', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fixed', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('IM', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('productCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Product', to_field='code')),
            ],
        ),
    ]
