# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0015_otherexpense_productionexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthAndYear', models.CharField(max_length=7, unique=True)),
                ('costCenter', models.CharField(max_length=9)),
                ('monthAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('costElement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.CostElement', to_field='name')),
                ('costType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.CostType', to_field='name')),
                ('deliveryMethod', models.ManyToManyField(blank=True, to='reporting.DeliveryMethod')),
                ('productType', models.ManyToManyField(blank=True, to='reporting.ProductType')),
                ('subpackage', models.ManyToManyField(blank=True, to='reporting.Subpackage')),
                ('warehouseCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Warehouse', to_field='code')),
            ],
        ),
    ]
