# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0016_costelement_costtype_distribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9)),
                ('costElement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.CostElement', to_field='name')),
                ('costType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.CostType', to_field='name')),
                ('deliveryMethod', models.ManyToManyField(blank=True, to='reporting.DeliveryMethod')),
                ('productType', models.ManyToManyField(blank=True, to='reporting.ProductType')),
                ('subpackage', models.ManyToManyField(blank=True, to='reporting.Subpackage')),
                ('warehouseCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Warehouse', to_field='code')),
            ],
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='costElement',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='costType',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='deliveryMethod',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='productType',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='subpackage',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='warehouseCode',
        ),
        migrations.AddField(
            model_name='distribution',
            name='monthVolume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='distribution',
            name='month_tKm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='distribution',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='costCenter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reporting.CostCenter'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='monthAndYear',
            field=models.CharField(max_length=7),
        ),
    ]
