# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0018_auto_20160224_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productname',
            name='commonName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
