# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0020_auto_20160224_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='salesRepresentative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.SalesRepresentative', to_field='name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='shipToCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.Unification', to_field='code'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='soldToCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reporting.Unification', to_field='code'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transportCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.Transport', to_field='code'),
        ),
    ]
