# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0021_auto_20160224_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionexpense',
            name='productCode',
        ),
        migrations.AddField(
            model_name='productionexpense',
            name='productName',
            field=models.ForeignKey(default='Null', on_delete=django.db.models.deletion.CASCADE, to='reporting.ProductName', to_field='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionexpense',
            name='warehouseCode',
            field=models.ForeignKey(default='Null', on_delete=django.db.models.deletion.CASCADE, to='reporting.Warehouse', to_field='code'),
            preserve_default=False,
        ),
    ]
