# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0022_auto_20160225_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productname',
            name='commonName',
        ),
    ]
