# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0023_remove_productname_commonname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFromDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='productCode',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='productCode',
        ),
        migrations.AddField(
            model_name='prediction',
            name='productName',
            field=models.ForeignKey(default='Null', on_delete=django.db.models.deletion.CASCADE, to='reporting.ProductName', to_field='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='productName',
            field=models.ForeignKey(default='Null', on_delete=django.db.models.deletion.CASCADE, to='reporting.ProductName', to_field='name'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.ManyToManyField(blank=True, to='reporting.ProductFromDB'),
        ),
    ]
