# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0024_auto_20160225_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='shippedVolume',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=15),
            preserve_default=False,
        ),
    ]
