# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0025_auto_20160226_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='productName',
        ),
        migrations.AddField(
            model_name='transaction',
            name='productCode',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='reporting.ProductFromDB', to_field='code'),
            preserve_default=False,
        ),
    ]
