# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0026_auto_20160226_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
