# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0027_auto_20160301_1544'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sap',
            new_name='ShipToFromDB',
        ),
        migrations.RenameModel(
            old_name='JD',
            new_name='SoldToFromDB',
        ),
        migrations.RemoveField(
            model_name='unification',
            name='jdCode',
        ),
        migrations.RemoveField(
            model_name='unification',
            name='sapCode',
        ),
        migrations.AddField(
            model_name='shipto',
            name='codeFromDB',
            field=models.ManyToManyField(to='reporting.ShipToFromDB'),
        ),
        migrations.AddField(
            model_name='shipto',
            name='name',
            field=models.CharField(default='Null', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soldto',
            name='codeFromDB',
            field=models.ManyToManyField(to='reporting.SoldToFromDB'),
        ),
        migrations.AddField(
            model_name='soldto',
            name='name',
            field=models.CharField(default='Null', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delivery',
            name='shipToCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.ShipTo', to_field='code'),
        ),
        migrations.AlterField(
            model_name='shipto',
            name='code',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='soldto',
            name='code',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='shipToCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.ShipTo', to_field='code'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='soldToCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.SoldTo', to_field='code'),
        ),
        migrations.DeleteModel(
            name='Unification',
        ),
    ]
