# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0028_auto_20160301_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipto',
            name='PSA',
        ),
        migrations.RemoveField(
            model_name='shipto',
            name='codeFromDB',
        ),
        migrations.RemoveField(
            model_name='shipto',
            name='region',
        ),
        migrations.RemoveField(
            model_name='soldto',
            name='CVM',
        ),
        migrations.RemoveField(
            model_name='soldto',
            name='codeFromDB',
        ),
        migrations.RemoveField(
            model_name='soldto',
            name='group',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='shipToCode',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='shipToCode',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='soldToCode',
        ),
        migrations.DeleteModel(
            name='ShipTo',
        ),
        migrations.DeleteModel(
            name='SoldTo',
        ),
    ]
