# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0029_auto_20160302_0837'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShipToFromDB',
        ),
        migrations.DeleteModel(
            name='SoldToFromDB',
        ),
    ]
