# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0030_auto_20160302_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('PSA', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.PSA', to_field='code')),
            ],
        ),
        migrations.CreateModel(
            name='ShipToFromDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SoldTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('CVM', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.CVM', to_field='code')),
            ],
        ),
        migrations.CreateModel(
            name='SoldToFromDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='soldto',
            name='codeFromDB',
            field=models.ManyToManyField(to='reporting.SoldToFromDB'),
        ),
        migrations.AddField(
            model_name='soldto',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.Group', to_field='code'),
        ),
        migrations.AddField(
            model_name='shipto',
            name='codeFromDB',
            field=models.ManyToManyField(to='reporting.ShipToFromDB'),
        ),
        migrations.AddField(
            model_name='shipto',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.Region', to_field='name'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='shipToCode',
            field=models.ForeignKey(default='Null', on_delete=django.db.models.deletion.CASCADE, to='reporting.ShipTo', to_field='code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='shipToCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.ShipTo', to_field='code'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='soldToCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.SoldTo', to_field='code'),
        ),
    ]
