# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0034_auto_20160303_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipto',
            name='PSA',
            field=models.ManyToManyField(blank=True, to='reporting.PSA'),
        ),
        migrations.AlterField(
            model_name='shipto',
            name='region',
            field=models.ForeignKey(blank=True, default='Null', on_delete=django.db.models.deletion.CASCADE, to='reporting.Region', to_field='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipto',
            name='salesRepresentative',
            field=models.ManyToManyField(blank=True, to='reporting.SalesRepresentative'),
        ),
    ]
