# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0036_auto_20160304_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipto',
            name='region',
        ),
    ]
